using ImageSeg.Domain.Identity.Entities;
using ImageSeg.Domain.Images.Entities;
using ImageSeg.Domain.MaskGroups.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace ImageSeg.Infrastructure.Persistence;

/// <summary>
/// Spec §2.3. One context, every feature area - ImageTasks, MaskGroups, and the standard
/// ASP.NET Core Identity schema, generated by <c>IdentityDbContext&lt;ApplicationUser, IdentityRole, string&gt;</c>.
/// This is the single Postgres database the spec targets (spec §11): no separate identity
/// store, no separate read/write databases.
/// </summary>
public class AppDbContext : IdentityDbContext<ApplicationUser, IdentityRole, string>
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<ImageTask> ImageTasks => Set<ImageTask>();
    public DbSet<MaskGroup> MaskGroups => Set<MaskGroup>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        base.OnModelCreating(b); // Identity's own table mappings (AspNetUsers, AspNetUserLogins, ...)

        b.Entity<ImageTask>(e =>
        {
            e.ToTable("ImageTasks");
            e.HasKey(x => x.Id);

            // Stored as text so the poller's raw SQL and the sweeper's ExecuteUpdate stay readable.
            e.Property(x => x.State)
             .HasConversion<string>()
             .HasMaxLength(32)
             .IsRequired();

            e.Property(x => x.OriginalFilePath).HasMaxLength(1024).IsRequired();
            e.Property(x => x.StorageProvider).HasMaxLength(32).IsRequired();

            e.Property(x => x.Operation)
             .HasConversion<string>()
             .HasMaxLength(16)
             .IsRequired();

            // Nullable: only Segment tasks carry a mode.
            e.Property(x => x.Mode).HasMaxLength(16);

            e.Property(x => x.OwnerId).HasMaxLength(450).IsRequired(); // matches AspNetUsers.Id length

            e.Property(x => x.ResultFilePath).HasMaxLength(1024);
            e.Property(x => x.ErrorMessage).HasMaxLength(2048);
            e.Property(x => x.IdempotencyKey).HasMaxLength(128);
            e.Property(x => x.CorrelationId).IsRequired();

            // Spec §2.1 - a real FK now that real user rows exist (was a bare, unenforced
            // string in the prototype).
            e.HasOne<ApplicationUser>()
             .WithMany()
             .HasForeignKey(x => x.OwnerId)
             .OnDelete(DeleteBehavior.Restrict);

            // Unique filtered index makes idempotent submission safe under concurrency, not
            // merely best-effort (spec §2.1's IdempotencyKey field).
            e.HasIndex(x => x.IdempotencyKey)
             .IsUnique()
             .HasDatabaseName("IX_ImageTasks_IdempotencyKey")
             .HasFilter("\"IdempotencyKey\" IS NOT NULL");

            // §4.1 claim predicate: WHERE State='Pending' AND (LockedUntilUtc IS NULL OR LockedUntilUtc < now()).
            e.HasIndex(x => new { x.State, x.LockedUntilUtc, x.CreatedAtUtc })
             .HasDatabaseName("IX_ImageTasks_Claim");

            // §4.5 StaleTaskSweeperWorker's predicate.
            e.HasIndex(x => new { x.State, x.UpdatedAtUtc })
             .HasDatabaseName("IX_ImageTasks_State_UpdatedAtUtc");

            // Drives "my uploaded images" listing (GET /api/images), newest first per owner.
            e.HasIndex(x => new { x.OwnerId, x.CreatedAtUtc })
             .HasDatabaseName("IX_ImageTasks_OwnerId_CreatedAtUtc");
        });

        b.Entity<MaskGroup>(e =>
        {
            e.ToTable("MaskGroups");
            e.HasKey(x => x.Id);

            e.Property(x => x.Name).HasMaxLength(256).IsRequired();
            e.Property(x => x.RegionIdsJson).IsRequired();

            // No formal FK to ImageTasks - application-enforced (spec §2.2), so a task and its
            // groups can be written to independently without EF FK-ordering concerns.
            e.HasIndex(x => x.ImageTaskId)
             .HasDatabaseName("IX_MaskGroups_ImageTaskId");
        });
    }
}
