// en.js — English strings, the reference translation.
//
// To add a language: copy this file to e.g. sr.js, translate every value
// (never the keys, never the {{placeholders}}), then point js/i18n.js at it
// — see the LOCALES map there. Nothing else in the app needs to change:
// every user-facing string in index.html goes through a data-i18n /
// data-i18n-attr attribute, and every dynamically generated string in the
// JS goes through the t() helper from js/i18n.js.

export const STRINGS = {
  common: {
    skipToControls: "Skip to controls",
    settings: "Settings",
    closeSettings: "Close settings",
    appearance: "Appearance",
    appearanceHint: "Light or dark theme",
    themeLight: "Light",
    themeDark: "Dark",
    language: "Language",
    languageHint: "Interface language",
    open: "Open",
    delete: "Delete",
    cancel: "Cancel",
    moreInfo: "More info",
  },

  auth: {
    login: {
      title: "Sign in to Maskwork",
      emailLabel: "Email",
      passwordLabel: "Password",
      submit: "Sign in",
      google: "Continue with Google",
      noAccount: "No account?",
      registerLink: "Register",
    },
    register: {
      title: "Create an account",
      emailLabel: "Email",
      passwordLabel: "Password",
      submit: "Create account",
      haveAccount: "Already have an account?",
      signinLink: "Sign in",
    },
    twofactor: {
      title: "Enter your code",
      hint: "Open your authenticator app and enter the 6-digit code for this account.",
      codeLabel: "Authentication code",
      submit: "Verify",
      back: "Back to sign in",
    },
  },

  masthead: {
    title: "Maskwork",
    subtitle: "Find the wall, or pick the regions yourself. Repaint only those pixels.",
    newPhoto: "New photo",
    signOut: "Sign out",
    menu: "Menu",
    closeMenu: "Close menu",
    moreTools: "More tools land here as they ship.",
  },

  stage: {
    ariaLabel: "Image preview",
    footEdit: "Preview is downscaled for smooth dragging. Export renders at full resolution.",
    footSelect: "Click a surface to add it. Click it again to drop it. Several regions can make up one wall.",
  },

  well: {
    resumeHint: "Click \u201COpen\u201D in the panel to continue this session.",
    emptyTitle: "No image loaded",
    emptyHint: "Drop a photo into the panel and choose how the surface should be found.",
    working: "Working\u2026",
    pickerAriaLabel: "Click a region of the photo to add it to the selection",
    compareBefore: "Before",
    compareAfter: "After",
    compareSliderAria: "Drag to compare the photo before and after your edits",
    compareToggle: "Before / After",
    zoomOutAria: "Zoom out",
    zoomInAria: "Zoom in",
    zoomResetTitle: "Reset zoom",
  },

  jobForm: {
    step1Title: "Load a photo",
    dropAriaLabel: "Choose an image, or drop one here",
    dropLabel: "Choose an image or drop it here",
    dropMeta: "PNG, JPEG or WebP \u00B7 up to 10 MB",
    change: "Change",
    step2Title: "How should the surface be found?",
    operationAriaLabel: "Operation",
    opSegmentName: "Find the wall",
    opSegmentDesc: "A fixed model looks for wall surfaces on its own. Nothing to click.",
    opRegionsName: "Pick regions myself",
    opRegionsDesc: "The photo is split into regions. You click the ones that make up the surface, and save the set.",
    modeLabel: "Which side of the wall?",
    modeHint: "Interior for rooms, exterior for facades. The model is trained differently for each.",
    submit: "Start",
    reuseNote: "Using the photo already loaded \u2014 no re-upload.",
    sizeNote: "Size and type are checked here for speed. The server checks again, and its answer is the one that counts.",
    sizeNoteLabel: "Why this gets checked twice",
    resumeToggle: "Resume an earlier session",
    resumeNote: "Opening a job here brings back the photo, the mask or regions, and every saved selection \u2014 no need to pick the photo again.",
    resumeNoteLabel: "What resuming brings back",
    resumeHeading: "Your recent jobs",
    resumeRefresh: "Refresh",
    resumeEmpty: "Nothing here yet.",
    deleteJobTitle: "Delete this job?",
    deleteJobMessage: "This deletes the {{job}} job. This can't be undone.",
    mode: {
      interior: "Interior",
      exterior: "Exterior",
    },
  },

  tracking: {
    title: "Working",
    statusQueued: "Queued",
    stepQueued: "Queued",
    stepReading: "Reading photo",
    stepFinding: "Finding surface",
    workingAria: "Working",
    runningFor: "Running for",
    slowNote: "Still going. Long queues and large photos both do this \u2014 the job is not lost.",
    stopWaiting: "Stop waiting",
    reopeningSession: "Reopening the session",
  },

  error: {
    title: "Something went wrong",
    tryAgain: "Try again",
    startOver: "Start over",
    newImage: "New image",
    uploadRejected: "The server rejected that upload.",
    exportFailed: "The export failed.",
    jobListFailed: "The job list could not be loaded.",
    deleteJobFailed: "Could not delete that job.",

    resultUnreadable: {
      title: "The result cannot be read",
      message: "The image downloaded, but the browser will not let this page read its pixels. The server needs to send CORS headers that allow this origin, on both the result response and the storage URL it redirects to.",
    },
    noWallFound: {
      title: "No wall found",
      message: "The {{mode}} model did not find a wall in this photo.",
      otherHint: " Photos of the other kind usually need the {{other}} model.",
      tryOtherInstead: "Try {{other}} instead",
      pickByHand: "Pick regions by hand",
    },
    noRegions: {
      title: "No regions came back",
      message: "The model split this photo into nothing selectable. A larger or less blurry photo usually works better.",
      findAutomatically: "Find the wall automatically",
    },
    rateLimited: {
      title: "Too many requests",
      messageGroup: "Saving selections shares the same rate limit as uploading images, and it has run out. Nothing was lost \u2014 the selection is still here.",
      messageSubmit: "You have hit the rate limit. Submitting again unlocks automatically.",
      wait: "Wait {{seconds}}s",
      backToSelection: "Back to the selection",
      submitAgain: "Submit again",
    },
    notReady: {
      title: "The result is not ready yet",
      message: "The job reports as finished, but its output has not landed in storage yet. This usually clears in a few seconds.",
      checkAgain: "Check again",
    },
    notFound: {
      titleSession: "That session no longer exists",
      titleJob: "That job is not available",
      messageOriginal: "The server has no record of this job anymore.",
      messageScoped: "The server will not return this job for the current sign-in. It may have expired, or it may belong to a different account.",
      messageGeneric: "The server no longer has this job. Submitting the photo again creates a fresh one.",
      back: "Back",
    },
    noConnection: {
      title: "No connection to the server",
      messageResult: "The job finished, but its output could not be downloaded. It is still on the server.",
      messageOriginal: "The photo could not be downloaded. The session is still on the server.",
      messageGeneric: "The request did not reach the server. Check the connection and try again.",
      downloadAgain: "Download it again",
    },
    serverProblem: {
      title: "The server had a problem",
      message: "Something failed on the server side. Trying again often works.",
    },
    jobFailed: {
      title: "The job failed",
      messageGeneric: "The server could not finish the {{job}} job for this photo.",
    },
    takingLong: {
      title: "This is taking unusually long",
      message: "No result after {{minutes}} minutes. The job may still finish \u2014 waiting keeps checking, and stopping leaves it running on the server.",
      keepWaiting: "Keep waiting",
      stopAndStartOver: "Stop and start over",
    },
    stoppedWaiting: {
      title: "Stopped waiting",
      message: "The job is still running on the server. Checking again picks it back up.",
    },
  },

  select: {
    title: "Choose the surface",
    hint: "Click regions in the photo. A wall is often three or four of them \u2014 a lit part, a shaded part, the strip under a window.",
    nameLabel: "Name this selection",
    namePlaceholder: "Living room wall",
    editingNote: "Editing a saved selection. Saving replaces it.",
    startNew: "Start a new one",
    useSelection: "Edit these regions",
    saveSelection: "Save selection",
    clear: "Clear",
    saveHint: "Editing works straight away \u2014 saving is only about getting the selection back later.",
    savedHeading: "Saved selections",
    savedEmpty: "None saved for this photo yet.",
    backToEdit: "Back to editing",
    regionsCount: "{{count}} region{{plural}}",
    coveragePercent: "{{percent}}% of frame",
    removeRegionTitle: "Remove this region",
    savedSelectionsRestored: "{{count}} saved selection{{plural}} restored.",
    regionsFound: "{{count}} regions found. Click the ones that make up the surface.",
    savedGroup: "Saved \u201C{{name}}\u201D.",
    deleteGroupTitle: "Delete this selection?",
    deleteGroupMessage: "This deletes \u201C{{name}}\u201D. This can't be undone.",
    selectionDeleted: "Selection deleted.",
    jobDeleted: "Job deleted.",
    readyToEdit: "{{label}} is ready to edit.",
  },

  edit: {
    title: "Edit the surface",
    tabSurfaces: "Surfaces",
    tabColor: "Colour",
    tabAdjust: "Adjust",
    tabMask: "Mask",
    tabExport: "Export",
    surfacesHeading: "Surfaces",
    addSurface: "Add another surface",
    colorLabel: "Colour",
    keepOriginal: "Keep original",
    customColorAria: "Custom colour",
    presetColorsAria: "Preset colours",
    intensityLabel: "Colour intensity",
    intensityHint: "Colour applies as a flat, full colour at 100%. Lower the intensity to blend it back toward the original.",
    blendModeLabel: "Blend mode",
    blendModeHint: "How the new colour meets the wall underneath. Normal is a flat, literal colour. Multiply, Soft Light, and Overlay let the original's own shading and texture show back through.",
    blendNormal: "Normal",
    blendMultiply: "Multiply",
    blendSoftLight: "Soft Light",
    blendOverlay: "Overlay",
    specularLabel: "Specular highlights",
    specularHint: "Keeps the wall's own shine and light reflections visible on top of the new colour or texture, for a more photorealistic finish.",
    hueLabel: "Hue shift",
    satLabel: "Saturation",
    texLabel: "Texture",
    texStrengthLabel: "Texture strength",
    texRotationLabel: "Texture rotation",
    texScaleLabel: "Texture size",
    texScaleHint: "How large the tile pattern reads on the wall — smaller for a finer, more detailed repeat, larger for bigger bricks or planks.",
    texRotationHint: "Turn the tile to match the angle of the wall.",
    texDepthLabel: "Texture depth",
    texDepthHint: "One side closer, the other farther \u2014 for a wall photographed at an angle.",
    warpLabel: "Perspective warp",
    warpHint: "Drag the handles on the photo to fit the texture to the wall's actual angle \u2014 a real perspective fit, not just a slider. Add rows or columns for a wall that isn't one flat plane.",
    warpReset: "Reset warp",
    warpRowsLabel: "Rows",
    warpColsLabel: "Columns",
    warpAddRow: "Add row",
    warpRemoveRow: "Remove row",
    warpAddCol: "Add column",
    warpRemoveCol: "Remove column",
    showMaskEdge: "Show the mask edge",
    resetSurface: "Reset this surface",
    download: "Download PNG",
    pngSaved: "PNG saved at full resolution.",
    undo: "Undo",
    redo: "Redo",
    brushLabel: "Brush & Eraser",
    brushHint: "Draw straight on the photo to add to the mask, or erase to take away — fixes edges, corners, and spots the automatic selection missed.",
    brushModeBrush: "Brush",
    brushModeEraser: "Eraser",
    brushSizeLabel: "Brush size",
    magnifierToggle: "Magnifier while drawing",
    magnifierHint: "Shows a zoomed-in peek near your finger or cursor while you draw — easier to land exactly on an edge, especially on a phone.",
    brushDrawHint: "Draw directly on the photo above to fine-tune the mask. Undo/redo (top-left of the photo) covers every stroke.",
    growShrinkLabel: "Grow / Shrink",
    growShrinkHint: "Pushes the mask's edge out or pulls it in by a number of pixels — quick way to clear a thin sliver of wall the selection missed, or pull back from something it caught by mistake.",
    featherLabel: "Feather",
    featherHint: "Softens the mask's edge into a gradual blend instead of a hard cut — smooths a harsh line at the ceiling or floor and helps colour or texture fade naturally into the untouched photo.",
    exportFinalLabel: "Final image",
    exportFinalHint: "The photo with every edit applied, at full resolution.",
    exportCompareLabel: "Before / After",
    exportCompareHint: "One image, the original and the edited version side by side at full resolution — ready to send to a client or post.",
    downloadCompare: "Download Before/After",
    exportMaskLabel: "Mask",
    exportMaskHint: "The selected surface on its own, white on a transparent background — for touching up in Photoshop or GIMP.",
    exportMaskNote: "Exports whichever surface is selected in the Surfaces tab.",
    downloadMask: "Download mask (PNG)",
    compareSaved: "Before/After image saved at full resolution.",
    maskSaved: "Mask saved as PNG.",
    compareExportFailed: "The Before/After export failed.",
    maskExportFailed: "The mask export failed.",
    noActiveSurface: "Pick a surface first.",
    colorOffReadout: "off",
    moveUp: "Move up",
    moveDown: "Move down",
    moveUpAria: "Move {{label}} up",
    moveDownAria: "Move {{label}} down",
  },
};
